### PR TITLE
chore: implement full CSP support

### PR DESCRIPTION
**Pull request by StoyanGoranov**
Implementing CSP compatibility features and fixes.

The unsafe-inline keyword is no longer required in the "style-src".

Fixes applied to EditorTemplates when global defer is used.

### CODE REVIEW

**Comment by mihaela-lukanova** [comment]
The editor templates of "Category" and "Country" fields in the "Demo_Overview_CSP" are not activated. Also, update the editors of the rets of the fields to be Kendo editors.
image

**Review by mihaela-lukanova — CHANGES_REQUESTED** [review]
The editor templates of "Category" and "Country" fields in the "Demo_Overview_CSP" are not activated. Also, update the editors of the rets of the fields to be Kendo editors.
image

**Comment by StoyanGoranov** [comment]
> The editor templates of "Category" and "Country" fields in the "Demo_Overview_CSP" are not activated. Also, update the editors of the rets of the fields to be Kendo editors. image

Issue seems to be caused by global defer in **Program.cs**:
`
builder.Services.AddKendo(x =>
{
    x.DeferToScriptFiles = true;
});
`

`
app.UseMiddleware<KendoDeferredScriptsMiddleware>();
`
since without these configurations the EditorTemplates are used correctly.
image

**Comment by StoyanGoranov** [comment]
To correctly initialize EditorTemplates in Grid deferred to a script file you need to:
1. Configure the editor ->
`
        @(Html.Kendo().Template().AddComponent(x => x.NumericTextBoxFor(m => m)
              .HtmlAttributes(new { style = "width:100%" })
              .HtmlAttributes(new { title = Html.ViewContext.ViewData.TemplateInfo.GetFullHtmlFieldName("") }))
        )
`
2. Configure the column -> 
`
       columns.Bound(p => p.UnitsInStock).Title("Units").Width(105).EditorTemplateComponentName("Number");
`

However, the Editor Templates are still not present in data-bound Components like DropDownLists.

**Review by mihaela-lukanova — APPROVED** [review]

**Pull request merged**
